version: '3'
services:
  gateway:
    image: gateway
    ports:
      - "8081:8081"
    networks:
      - my-network
    depends_on:
      - front

networks:
  my-network:
    driver: bridge